# Generated by Django 3.1.3 on 2021-10-23 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('plant_type', models.CharField(choices=[('Vegetable', 'Vegetable'), ('Flowering', 'Flowering')], default='Flowering', max_length=20)),
                ('imagefile', models.ImageField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order_plant1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=25)),
                ('qty', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('plant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nursery.add_plant')),
            ],
        ),
    ]
